# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-02 14:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20161202_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='prescriptions',
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.Patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 2, 15, 54, 10, 754367), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='temp_check_in_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 2, 14, 54, 10, 750367)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='temp_check_out_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 2, 14, 54, 10, 750367)),
        ),
    ]
