# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-03 00:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20161202_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescriber',
        ),
        migrations.AddField(
            model_name='patient',
            name='prescriptions',
            field=models.ManyToManyField(to='health.Prescription'),
        ),
        migrations.AddField(
            model_name='reason',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='health.Hospital'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 3, 1, 56, 4, 58221), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='temp_check_in_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 3, 0, 56, 4, 51215)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='temp_check_out_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 3, 0, 56, 4, 51215)),
        ),
    ]
