# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-04 18:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_auto_20161203_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='number_unique_patient_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospitals_visited',
            field=models.ManyToManyField(default=None, related_name='_patient_hospitals_visited_+', to='health.Hospital'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 4, 19, 3, 18, 429809), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_id',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='temp_check_in_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 4, 18, 3, 18, 421804)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='temp_check_out_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 4, 18, 3, 18, 421804)),
        ),
    ]
